services:
  postgres:
    image: postgres
    volumes:
      - ./docker-compose/postgeres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: powerpilot
      POSTGRES_USER: powerpilot
      POSTGRES_PASSWORD: iPorGUNTrapa
    ports:
        - 5432:5432
    networks:
      - powerpilot
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    command: /bin/bash -c "until pg_isready -U powerpilot -p 5432; do sleep 1; done; psql -U powerpilot -c 'CREATE DATABASE powerpilot;'"
  powerpilot:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - port=8000
    image: powerpilot
    container_name: powerpilot
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - 8000:80
    networks:
      - powerpilot
networks:
    powerpilot:
