services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: powerpilot
      POSTGRES_USER: powerpilot
      POSTGRES_PASSWORD: iPorGUNTrapa
    networks:
      - powerpilot
  powerpilot:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - port=8000
    image: powerpilot
    container_name: powerpilot
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - 8000:80
    networks:
      - powerpilot
networks:
    powerpilot:
