services:
  powerpilot:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - port=8000
    image: powerpilot
    container_name: powerpilot
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - 8000:80
    networks:
      - powerpilot
  mysql:
    image: mysql:latest
    container_name: powerpilot-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: powerpilot
      MYSQL_USER: powerpilot
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: admin.root
    ports:
      - 33068:3306
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
    networks:
      - powerpilot
networks:
    powerpilot:
